/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppStrategyRouteImport } from './routes/_app.strategy'
import { Route as AppMarketRouteImport } from './routes/_app.market'
import { Route as AppHoldingsRouteImport } from './routes/_app.holdings'
import { Route as AppAccountsRouteImport } from './routes/_app.accounts'
import { Route as AppHoldingsSymbolRouteImport } from './routes/_app.holdings.$symbol'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStrategyRoute = AppStrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppHoldingsRoute = AppHoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppHoldingsSymbolRoute = AppHoldingsSymbolRouteImport.update({
  id: '/$symbol',
  path: '/$symbol',
  getParentRoute: () => AppHoldingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/accounts': typeof AppAccountsRoute
  '/holdings': typeof AppHoldingsRouteWithChildren
  '/market': typeof AppMarketRoute
  '/strategy': typeof AppStrategyRoute
  '/holdings/$symbol': typeof AppHoldingsSymbolRoute
}
export interface FileRoutesByTo {
  '/accounts': typeof AppAccountsRoute
  '/holdings': typeof AppHoldingsRouteWithChildren
  '/market': typeof AppMarketRoute
  '/strategy': typeof AppStrategyRoute
  '/': typeof AppIndexRoute
  '/holdings/$symbol': typeof AppHoldingsSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/holdings': typeof AppHoldingsRouteWithChildren
  '/_app/market': typeof AppMarketRoute
  '/_app/strategy': typeof AppStrategyRoute
  '/_app/': typeof AppIndexRoute
  '/_app/holdings/$symbol': typeof AppHoldingsSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/holdings'
    | '/market'
    | '/strategy'
    | '/holdings/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accounts'
    | '/holdings'
    | '/market'
    | '/strategy'
    | '/'
    | '/holdings/$symbol'
  id:
    | '__root__'
    | '/_app'
    | '/_app/accounts'
    | '/_app/holdings'
    | '/_app/market'
    | '/_app/strategy'
    | '/_app/'
    | '/_app/holdings/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/strategy': {
      id: '/_app/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof AppStrategyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/market': {
      id: '/_app/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/holdings': {
      id: '/_app/holdings'
      path: '/holdings'
      fullPath: '/holdings'
      preLoaderRoute: typeof AppHoldingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/holdings/$symbol': {
      id: '/_app/holdings/$symbol'
      path: '/$symbol'
      fullPath: '/holdings/$symbol'
      preLoaderRoute: typeof AppHoldingsSymbolRouteImport
      parentRoute: typeof AppHoldingsRoute
    }
  }
}

interface AppHoldingsRouteChildren {
  AppHoldingsSymbolRoute: typeof AppHoldingsSymbolRoute
}

const AppHoldingsRouteChildren: AppHoldingsRouteChildren = {
  AppHoldingsSymbolRoute: AppHoldingsSymbolRoute,
}

const AppHoldingsRouteWithChildren = AppHoldingsRoute._addFileChildren(
  AppHoldingsRouteChildren,
)

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppHoldingsRoute: typeof AppHoldingsRouteWithChildren
  AppMarketRoute: typeof AppMarketRoute
  AppStrategyRoute: typeof AppStrategyRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppHoldingsRoute: AppHoldingsRouteWithChildren,
  AppMarketRoute: AppMarketRoute,
  AppStrategyRoute: AppStrategyRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
